### PR TITLE
Rename Method Tracer -> Method Timer

### PR DESCRIPTION
**Pull request by janxious**
Tracer is misleading.

### CODE REVIEW

**Comment by janxious** [comment]
This is going to warrant a minor version bump due to it being breaking change. I dont' feel like creating a shim so the old method name works is worthwhile since we released v1 in the last week.

**Review by jason-o-matic — CHANGES_REQUESTED** [review]
Looks good but I think at least a basic test should be added since the code is changing.

**Comment by janxious** [comment]
> Looks good but I think at least a basic test should be added since the code is changing.

I would swear on a holy text that I wrote one. I must of have git'ed myself out of that work.

**Comment by janxious** [comment]
Alright, looks like I just forgot to push those. sry boo

**Review by jason-o-matic — APPROVED** [review]

**Pull request merged**
